### ISSUE TITLE
Using your work in my environment

### ISSUE THREAD

**Issue by zwep** [choasma/HSIC-bottleneck#2]
Hi! 

I have seen your paper and wanted to give it a go on one of my own projects. Can you verify that an example of your method is shown in `source/hsicbt/core/train_hsic.py`?
So if I would replicate that work, I would be doing 'the right thing'?

**Comment by choasma** [comment]
SORRY, I just saw your comment. I'll update you shortly

**Comment by choasma** [comment]
hi @zwep, sorry for the long wait. Yes if you are working on that function, it is exactly the core function what we were doing in the paper across different tasks. For your convenience, I just prepared the API tester for you:
`tests/test_api_train_hsic.py`

Ideally, you should see H_hx decreases and H_hy increases respectively
Please let me know if you have any further issues

**Comment by choasma** [comment]
hi @zwep, please feel free to reopen this ticket or create new for any further question, thanks!
