### ISSUE TITLE
unable to run the code

### ISSUE THREAD

**Issue by msafwankhan** [choasma/HSIC-bottleneck#4]
Hi @choasma 

I am unable to build the solution. This seems like an issue with the directory structure.
I keep getting this error. 

`$ batch.sh
Traceback (most recent call last):
  File "./bin/run_hsicbt", line 3, in <module>
    from hsicbt.core.dispatcher import job_execution
ModuleNotFoundError: No module named 'hsicbt'
`

Am I missing something?

**Comment by choasma** [comment]
It's ok run it on my side. Were you running the batch.sh under the project root directory with the environment set, for instance `source env.sh`. To me, the module hsicbt path isn't added properly.

**Comment by choasma** [comment]
hi @msafwankhan 
I'm closing this, let me know if you have further issue or just simply create new one
